# Generated by Django 6.0.4 on 2026-04-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(verbose_name='Año')),
                ('km', models.PositiveIntegerField(verbose_name='Kilometraje')),
                ('fuel', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diesel'), ('ELECTRICO', 'Eléctrico'), ('HIBRIDO', 'Híbrido')], default='GASOLINA', max_length=20)),
                ('status', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVADO', 'Reservado'), ('VENDIDO', 'Vendido')], default='DISPONIBLE', max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Compra')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('market_price_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Mercado (IA)')),
                ('last_market_update', models.DateTimeField(blank=True, null=True, verbose_name='Última actualización de mercado')),
            ],
            options={
                'verbose_name': 'Coche',
                'verbose_name_plural': 'Coches',
                'ordering': ['-last_market_update'],
            },
        ),
    ]
